// <auto-generated />
using System;
using BancoSol.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BancoSol.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260416043312_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("BancoSol.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222101"),
                            Currency = "USD",
                            Name = "Gel Limpiador Facial Suave",
                            Price = 12.50m,
                            Sku = "SKU-101",
                            Stock = 50
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222102"),
                            Currency = "USD",
                            Name = "Agua Micelar Desmaquillante 400ml",
                            Price = 10.90m,
                            Sku = "SKU-102",
                            Stock = 40
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222103"),
                            Currency = "USD",
                            Name = "Espuma Limpiadora Piel Sensible",
                            Price = 14.75m,
                            Sku = "SKU-103",
                            Stock = 35
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222104"),
                            Currency = "USD",
                            Name = "Tonico Facial Hidratante con Rosa",
                            Price = 18.00m,
                            Sku = "SKU-104",
                            Stock = 28
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222105"),
                            Currency = "USD",
                            Name = "Serum Vitamina C Antimanchas",
                            Price = 29.99m,
                            Sku = "SKU-105",
                            Stock = 22
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222106"),
                            Currency = "USD",
                            Name = "Mascarilla Arcilla Purificante",
                            Price = 11.50m,
                            Sku = "SKU-106",
                            Stock = 45
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222107"),
                            Currency = "USD",
                            Name = "Exfoliante Facial de Azucar",
                            Price = 9.95m,
                            Sku = "SKU-107",
                            Stock = 30
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222108"),
                            Currency = "USD",
                            Name = "Crema Hidratante SPF 30 Dia",
                            Price = 22.00m,
                            Sku = "SKU-108",
                            Stock = 60
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222109"),
                            Currency = "USD",
                            Name = "Contorno de Ojos Anti-Age",
                            Price = 34.50m,
                            Sku = "SKU-109",
                            Stock = 18
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222110"),
                            Currency = "USD",
                            Name = "Aceite de Jojoba Desmaquillante",
                            Price = 15.80m,
                            Sku = "SKU-110",
                            Stock = 25
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222111"),
                            Currency = "EUR",
                            Name = "Bálsamo Limpiador con Aceite de Coco",
                            Price = 17.25m,
                            Sku = "SKU-111",
                            Stock = 32
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222112"),
                            Currency = "EUR",
                            Name = "Parches Ojeras con Acido Hialuronico",
                            Price = 8.50m,
                            Sku = "SKU-112",
                            Stock = 55
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222113"),
                            Currency = "EUR",
                            Name = "Mascarilla de Lámina Hidrogel",
                            Price = 5.99m,
                            Sku = "SKU-113",
                            Stock = 70
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222114"),
                            Currency = "EUR",
                            Name = "Serum Retinol Noche",
                            Price = 39.90m,
                            Sku = "SKU-114",
                            Stock = 15
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222115"),
                            Currency = "EUR",
                            Name = "Crema Noche Regeneradora con Colageno",
                            Price = 27.00m,
                            Sku = "SKU-115",
                            Stock = 20
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222116"),
                            Currency = "EUR",
                            Name = "Protector Solar Facial 50+ Sin Color",
                            Price = 19.50m,
                            Sku = "SKU-116",
                            Stock = 48
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222117"),
                            Currency = "EUR",
                            Name = "Protector Solar Facial 50+ Con Color",
                            Price = 21.00m,
                            Sku = "SKU-117",
                            Stock = 38
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222118"),
                            Currency = "EUR",
                            Name = "Serum Niacinamida Poros Minimizador",
                            Price = 24.99m,
                            Sku = "SKU-118",
                            Stock = 33
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222119"),
                            Currency = "EUR",
                            Name = "Tónico Exfoliante con AHA BHA",
                            Price = 32.00m,
                            Sku = "SKU-119",
                            Stock = 19
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222120"),
                            Currency = "EUR",
                            Name = "Limpiador Facial en Polvo Enzimático",
                            Price = 16.75m,
                            Sku = "SKU-120",
                            Stock = 27
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222121"),
                            Currency = "BOB",
                            Name = "Cepillo Limpiador Facial Silicona",
                            Price = 22.50m,
                            Sku = "SKU-121",
                            Stock = 14
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222122"),
                            Currency = "BOB",
                            Name = "Roller de Cuarzo Facial Anti-Age",
                            Price = 150.00m,
                            Sku = "SKU-122",
                            Stock = 21
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222123"),
                            Currency = "BOB",
                            Name = "Gua Sha de Jade Facial",
                            Price = 120.00m,
                            Sku = "SKU-123",
                            Stock = 18
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222124"),
                            Currency = "BOB",
                            Name = "Mascara Vapor Facial Hidratante",
                            Price = 380.00m,
                            Sku = "SKU-124",
                            Stock = 8
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222125"),
                            Currency = "BOB",
                            Name = "Kit Parches Anti-Acne Puntual",
                            Price = 45.00m,
                            Sku = "SKU-125",
                            Stock = 90
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222126"),
                            Currency = "BOB",
                            Name = "Crema BB Unificadora Tono Natural",
                            Price = 88.00m,
                            Sku = "SKU-126",
                            Stock = 42
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222127"),
                            Currency = "BOB",
                            Name = "Serum Peptidos Reafirmante",
                            Price = 520.00m,
                            Sku = "SKU-127",
                            Stock = 12
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222128"),
                            Currency = "BOB",
                            Name = "Aceite Facial Squalane Puro",
                            Price = 210.00m,
                            Sku = "SKU-128",
                            Stock = 23
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222129"),
                            Currency = "BOB",
                            Name = "Crema Anti-Manchas Kojic Acid",
                            Price = 175.00m,
                            Sku = "SKU-129",
                            Stock = 16
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222130"),
                            Currency = "BOB",
                            Name = "Serum Acido Hialuronico Triple",
                            Price = 290.00m,
                            Sku = "SKU-130",
                            Stock = 29
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222131"),
                            Currency = "USD",
                            Name = "Limpiador Facial Espuma Acne",
                            Price = 13.00m,
                            Sku = "SKU-131",
                            Stock = 36
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222132"),
                            Currency = "USD",
                            Name = "Tónico Agua de Rosas Calmante",
                            Price = 9.50m,
                            Sku = "SKU-132",
                            Stock = 44
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222133"),
                            Currency = "USD",
                            Name = "Mascarilla Carbón Activado Poros",
                            Price = 11.00m,
                            Sku = "SKU-133",
                            Stock = 38
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222134"),
                            Currency = "USD",
                            Name = "Serum Aclarante Manchas Oscuras",
                            Price = 26.50m,
                            Sku = "SKU-134",
                            Stock = 17
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222135"),
                            Currency = "USD",
                            Name = "Gel Contorno Ojos Descongestivo",
                            Price = 19.99m,
                            Sku = "SKU-135",
                            Stock = 20
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222136"),
                            Currency = "USD",
                            Name = "Crema Facial Piel Seca Intensa",
                            Price = 23.75m,
                            Sku = "SKU-136",
                            Stock = 31
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222137"),
                            Currency = "USD",
                            Name = "Mascarilla Vitamina E Nutridora",
                            Price = 10.25m,
                            Sku = "SKU-137",
                            Stock = 26
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222138"),
                            Currency = "USD",
                            Name = "Spray Fijador Maquillaje SPF",
                            Price = 14.90m,
                            Sku = "SKU-138",
                            Stock = 33
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222139"),
                            Currency = "USD",
                            Name = "Leche Limpiadora Desmaquillante",
                            Price = 11.80m,
                            Sku = "SKU-139",
                            Stock = 29
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222140"),
                            Currency = "USD",
                            Name = "Crema Facial Piel Mixta Equilibrante",
                            Price = 20.00m,
                            Sku = "SKU-140",
                            Stock = 37
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222141"),
                            Currency = "EUR",
                            Name = "Serum Ferment Galactomyces Glow",
                            Price = 28.00m,
                            Sku = "SKU-141",
                            Stock = 11
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222142"),
                            Currency = "EUR",
                            Name = "Mascarilla Aloe Vera Calmante",
                            Price = 7.90m,
                            Sku = "SKU-142",
                            Stock = 50
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222143"),
                            Currency = "EUR",
                            Name = "Exfoliante Enzimático Papaya",
                            Price = 13.50m,
                            Sku = "SKU-143",
                            Stock = 24
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222144"),
                            Currency = "EUR",
                            Name = "Crema Prebiótica Microbioma Facial",
                            Price = 36.00m,
                            Sku = "SKU-144",
                            Stock = 13
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222145"),
                            Currency = "EUR",
                            Name = "Agua Termal Calmante 150ml",
                            Price = 8.25m,
                            Sku = "SKU-145",
                            Stock = 65
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222146"),
                            Currency = "EUR",
                            Name = "Serum Efecto Tensor Lifting",
                            Price = 44.99m,
                            Sku = "SKU-146",
                            Stock = 9
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222147"),
                            Currency = "EUR",
                            Name = "Parches Nariz Puntos Negros",
                            Price = 4.50m,
                            Sku = "SKU-147",
                            Stock = 80
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222148"),
                            Currency = "EUR",
                            Name = "Crema Facial Aclarante Uniforme",
                            Price = 25.00m,
                            Sku = "SKU-148",
                            Stock = 22
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222149"),
                            Currency = "EUR",
                            Name = "Sérum Acido Glicólico 10%",
                            Price = 31.50m,
                            Sku = "SKU-149",
                            Stock = 14
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222150"),
                            Currency = "EUR",
                            Name = "Crema Colageno Marino Reparadora",
                            Price = 42.00m,
                            Sku = "SKU-150",
                            Stock = 18
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222151"),
                            Currency = "USD",
                            Name = "Limpiador Doble Fase Bifásico",
                            Price = 16.00m,
                            Sku = "SKU-151",
                            Stock = 27
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222152"),
                            Currency = "USD",
                            Name = "Mascarilla Dormir Sin Aclarado",
                            Price = 21.50m,
                            Sku = "SKU-152",
                            Stock = 19
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222153"),
                            Currency = "USD",
                            Name = "Serum Cobre Peptidos Reafirmante",
                            Price = 49.00m,
                            Sku = "SKU-153",
                            Stock = 8
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222154"),
                            Currency = "USD",
                            Name = "Crema Facial Matificante Piel Grasa",
                            Price = 17.80m,
                            Sku = "SKU-154",
                            Stock = 41
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222155"),
                            Currency = "USD",
                            Name = "Rodillo Facial Acero Inox Criogénico",
                            Price = 28.00m,
                            Sku = "SKU-155",
                            Stock = 12
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222156"),
                            Currency = "USD",
                            Name = "Dispositivo LED Facial Rejuvenecedor",
                            Price = 89.00m,
                            Sku = "SKU-156",
                            Stock = 5
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222157"),
                            Currency = "USD",
                            Name = "Toallitas Faciales Biodegradables x30",
                            Price = 6.50m,
                            Sku = "SKU-157",
                            Stock = 60
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222158"),
                            Currency = "USD",
                            Name = "Espátula Extracción Comedones",
                            Price = 12.00m,
                            Sku = "SKU-158",
                            Stock = 25
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222159"),
                            Currency = "USD",
                            Name = "Diadema Limpieza Facial Spa",
                            Price = 5.00m,
                            Sku = "SKU-159",
                            Stock = 55
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222160"),
                            Currency = "USD",
                            Name = "Spray Tónico Facial de Bambú",
                            Price = 11.25m,
                            Sku = "SKU-160",
                            Stock = 34
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222161"),
                            Currency = "EUR",
                            Name = "Crema Facial Granada Antioxidante",
                            Price = 33.00m,
                            Sku = "SKU-161",
                            Stock = 15
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222162"),
                            Currency = "EUR",
                            Name = "Mascarilla Dorada Antiedad Gold",
                            Price = 38.50m,
                            Sku = "SKU-162",
                            Stock = 10
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222163"),
                            Currency = "EUR",
                            Name = "Crema Labial Nutritiva con FPS",
                            Price = 6.99m,
                            Sku = "SKU-163",
                            Stock = 70
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222164"),
                            Currency = "EUR",
                            Name = "Serum Zinc Antiinflamatorio Acne",
                            Price = 22.75m,
                            Sku = "SKU-164",
                            Stock = 21
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222165"),
                            Currency = "EUR",
                            Name = "Crema Contorno Labios Anti-Arrugas",
                            Price = 27.50m,
                            Sku = "SKU-165",
                            Stock = 16
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222166"),
                            Currency = "EUR",
                            Name = "Aceite Facial Rosa Mosqueta Puro",
                            Price = 18.90m,
                            Sku = "SKU-166",
                            Stock = 28
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222167"),
                            Currency = "EUR",
                            Name = "Mascarilla Peel-Off Purificante",
                            Price = 9.75m,
                            Sku = "SKU-167",
                            Stock = 35
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222168"),
                            Currency = "EUR",
                            Name = "Gel Contorno Facial Efecto Frío",
                            Price = 15.00m,
                            Sku = "SKU-168",
                            Stock = 24
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222169"),
                            Currency = "EUR",
                            Name = "Crema Facial Onagra Piel Seca",
                            Price = 23.00m,
                            Sku = "SKU-169",
                            Stock = 19
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222170"),
                            Currency = "EUR",
                            Name = "Serum Gota Milagro Todo En Uno",
                            Price = 19.50m,
                            Sku = "SKU-170",
                            Stock = 30
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222171"),
                            Currency = "BOB",
                            Name = "Limpiador Facial Micelar con Prebióticos",
                            Price = 14.25m,
                            Sku = "SKU-171",
                            Stock = 26
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222172"),
                            Currency = "BOB",
                            Name = "Crema Solar Facial BB Mineral FPS50",
                            Price = 195.00m,
                            Sku = "SKU-172",
                            Stock = 32
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222173"),
                            Currency = "BOB",
                            Name = "Serum Ácido Ferúlico Vitamina E",
                            Price = 320.00m,
                            Sku = "SKU-173",
                            Stock = 10
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222174"),
                            Currency = "BOB",
                            Name = "Espuma Limpiadora Aminoácidos",
                            Price = 135.00m,
                            Sku = "SKU-174",
                            Stock = 22
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222175"),
                            Currency = "BOB",
                            Name = "Crema Noche con Bakuchiol Natural",
                            Price = 280.00m,
                            Sku = "SKU-175",
                            Stock = 14
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222176"),
                            Currency = "BOB",
                            Name = "Tónico Hidratante 7 Skin Method",
                            Price = 165.00m,
                            Sku = "SKU-176",
                            Stock = 17
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222177"),
                            Currency = "BOB",
                            Name = "Mascarilla Mugwort Calmante Acne",
                            Price = 98.00m,
                            Sku = "SKU-177",
                            Stock = 40
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222178"),
                            Currency = "BOB",
                            Name = "Crema Facial Manteca de Karité",
                            Price = 115.00m,
                            Sku = "SKU-178",
                            Stock = 25
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222179"),
                            Currency = "BOB",
                            Name = "Kit Rutina Coreana 5 Pasos",
                            Price = 490.00m,
                            Sku = "SKU-179",
                            Stock = 7
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222180"),
                            Currency = "BOB",
                            Name = "Dispositivo Ultrasonido Limpieza",
                            Price = 850.00m,
                            Sku = "SKU-180",
                            Stock = 4
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222181"),
                            Currency = "USD",
                            Name = "Sérum Centella Asiatica Cicatrizante",
                            Price = 18.75m,
                            Sku = "SKU-181",
                            Stock = 33
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222182"),
                            Currency = "USD",
                            Name = "Mascarilla Colágeno Oro 24K",
                            Price = 35.00m,
                            Sku = "SKU-182",
                            Stock = 12
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222183"),
                            Currency = "USD",
                            Name = "Crema Hidratante Ceramidas Barrera",
                            Price = 27.00m,
                            Sku = "SKU-183",
                            Stock = 20
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222184"),
                            Currency = "USD",
                            Name = "Ampolla Vitamina C Concentrada x7",
                            Price = 22.50m,
                            Sku = "SKU-184",
                            Stock = 15
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222185"),
                            Currency = "USD",
                            Name = "Crema Primer Hidratante Poros",
                            Price = 19.00m,
                            Sku = "SKU-185",
                            Stock = 28
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222186"),
                            Currency = "USD",
                            Name = "Agua Micelar Bifásica Waterproof",
                            Price = 13.50m,
                            Sku = "SKU-186",
                            Stock = 37
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222187"),
                            Currency = "USD",
                            Name = "Serum Azelaico Anti-Imperfecciones",
                            Price = 30.00m,
                            Sku = "SKU-187",
                            Stock = 11
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222188"),
                            Currency = "USD",
                            Name = "Tónico Anti-Poros Hamamelis",
                            Price = 10.00m,
                            Sku = "SKU-188",
                            Stock = 43
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222189"),
                            Currency = "USD",
                            Name = "Limpiador en Barra Facial Suave",
                            Price = 7.25m,
                            Sku = "SKU-189",
                            Stock = 50
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222190"),
                            Currency = "USD",
                            Name = "Kit Ampollas Hialuronico + Vitamina C",
                            Price = 38.00m,
                            Sku = "SKU-190",
                            Stock = 9
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222191"),
                            Currency = "EUR",
                            Name = "Aceite Limpiador Facial Oleo-Micelar",
                            Price = 16.00m,
                            Sku = "SKU-191",
                            Stock = 24
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222192"),
                            Currency = "EUR",
                            Name = "Crema Facial Antioxidante Resveratrol",
                            Price = 40.00m,
                            Sku = "SKU-192",
                            Stock = 13
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222193"),
                            Currency = "EUR",
                            Name = "Gel Crema Hidratante Piel Normal",
                            Price = 18.50m,
                            Sku = "SKU-193",
                            Stock = 31
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222194"),
                            Currency = "EUR",
                            Name = "Mascarilla Exfoliante AHA Glow",
                            Price = 24.75m,
                            Sku = "SKU-194",
                            Stock = 16
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222195"),
                            Currency = "EUR",
                            Name = "Parches Microneedle Acido Hialuronico",
                            Price = 14.00m,
                            Sku = "SKU-195",
                            Stock = 20
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222196"),
                            Currency = "EUR",
                            Name = "Crema Reparadora Barrera Noche",
                            Price = 32.50m,
                            Sku = "SKU-196",
                            Stock = 18
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222197"),
                            Currency = "EUR",
                            Name = "Gel Limpiador Salicílico Poros",
                            Price = 12.75m,
                            Sku = "SKU-197",
                            Stock = 39
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222198"),
                            Currency = "EUR",
                            Name = "Sérum Cafeína Ojeras Bolsas",
                            Price = 20.00m,
                            Sku = "SKU-198",
                            Stock = 22
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222199"),
                            Currency = "EUR",
                            Name = "Crema Facial Monodosis Sin Conservantes x10",
                            Price = 28.00m,
                            Sku = "SKU-199",
                            Stock = 8
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222200"),
                            Currency = "EUR",
                            Name = "Kit Ritual Completo Limpieza Facial",
                            Price = 55.00m,
                            Sku = "SKU-200",
                            Stock = 5
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333201"),
                            Currency = "USD",
                            Name = "Zapatilla Running Carbono Pro",
                            Price = 180.00m,
                            Sku = "SKU-201",
                            Stock = 12
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333202"),
                            Currency = "USD",
                            Name = "Zapatilla Trail Running Grip Max",
                            Price = 140.00m,
                            Sku = "SKU-202",
                            Stock = 18
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333203"),
                            Currency = "USD",
                            Name = "Zapatilla Entrenamiento Diario Foam",
                            Price = 95.00m,
                            Sku = "SKU-203",
                            Stock = 25
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333204"),
                            Currency = "USD",
                            Name = "Calcetines Running Compresion x3",
                            Price = 18.50m,
                            Sku = "SKU-204",
                            Stock = 60
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333205"),
                            Currency = "USD",
                            Name = "Calcetines Anti-Ampolla Running x2",
                            Price = 12.00m,
                            Sku = "SKU-205",
                            Stock = 55
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333206"),
                            Currency = "USD",
                            Name = "Short Running Ligero Hombre",
                            Price = 28.00m,
                            Sku = "SKU-206",
                            Stock = 35
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333207"),
                            Currency = "USD",
                            Name = "Short Running 2en1 Compresion",
                            Price = 34.00m,
                            Sku = "SKU-207",
                            Stock = 30
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333208"),
                            Currency = "USD",
                            Name = "Malla Larga Running Reflectante",
                            Price = 42.00m,
                            Sku = "SKU-208",
                            Stock = 22
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333209"),
                            Currency = "USD",
                            Name = "Camiseta Técnica Dry-Fit Running",
                            Price = 22.00m,
                            Sku = "SKU-209",
                            Stock = 40
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333210"),
                            Currency = "USD",
                            Name = "Camiseta Sin Mangas Running Ultra-Light",
                            Price = 19.50m,
                            Sku = "SKU-210",
                            Stock = 38
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333211"),
                            Currency = "EUR",
                            Name = "Gorra Running Ventilada Reflectante",
                            Price = 20.00m,
                            Sku = "SKU-211",
                            Stock = 45
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333212"),
                            Currency = "EUR",
                            Name = "Gorra Trail Running Visera Larga",
                            Price = 24.00m,
                            Sku = "SKU-212",
                            Stock = 28
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333213"),
                            Currency = "EUR",
                            Name = "Buff Multifuncional Running",
                            Price = 11.00m,
                            Sku = "SKU-213",
                            Stock = 50
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333214"),
                            Currency = "EUR",
                            Name = "Guantes Running Táctiles Invierno",
                            Price = 18.50m,
                            Sku = "SKU-214",
                            Stock = 20
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333215"),
                            Currency = "EUR",
                            Name = "Chaqueta Cortaviento Running Plegable",
                            Price = 65.00m,
                            Sku = "SKU-215",
                            Stock = 15
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333216"),
                            Currency = "EUR",
                            Name = "Chaleco Running Reflectante Nocturno",
                            Price = 30.00m,
                            Sku = "SKU-216",
                            Stock = 12
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333217"),
                            Currency = "EUR",
                            Name = "Cinturón Portador Running Bidón",
                            Price = 22.00m,
                            Sku = "SKU-217",
                            Stock = 24
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333218"),
                            Currency = "EUR",
                            Name = "Riñonera Running Ultra Ligera",
                            Price = 16.50m,
                            Sku = "SKU-218",
                            Stock = 32
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333219"),
                            Currency = "EUR",
                            Name = "Mochila Hidratación Trail 10L",
                            Price = 55.00m,
                            Sku = "SKU-219",
                            Stock = 10
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333220"),
                            Currency = "EUR",
                            Name = "Mochila Competición Running 5L",
                            Price = 70.00m,
                            Sku = "SKU-220",
                            Stock = 8
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333221"),
                            Currency = "BOB",
                            Name = "Reloj GPS Running Multideporte",
                            Price = 890.00m,
                            Sku = "SKU-221",
                            Stock = 7
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333222"),
                            Currency = "BOB",
                            Name = "Reloj Running GPS Básico",
                            Price = 580.00m,
                            Sku = "SKU-222",
                            Stock = 10
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333223"),
                            Currency = "BOB",
                            Name = "Banda Frecuencia Cardiaca Pectoral",
                            Price = 250.00m,
                            Sku = "SKU-223",
                            Stock = 14
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333224"),
                            Currency = "BOB",
                            Name = "Sensor Cadencia Zancada Running",
                            Price = 180.00m,
                            Sku = "SKU-224",
                            Stock = 9
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333225"),
                            Currency = "BOB",
                            Name = "Auriculares Sport IPX5 Running",
                            Price = 320.00m,
                            Sku = "SKU-225",
                            Stock = 20
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333226"),
                            Currency = "BOB",
                            Name = "Auriculares Bone Conduction Running",
                            Price = 550.00m,
                            Sku = "SKU-226",
                            Stock = 6
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333227"),
                            Currency = "BOB",
                            Name = "Porta Celular Brazo Running",
                            Price = 85.00m,
                            Sku = "SKU-227",
                            Stock = 40
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333228"),
                            Currency = "BOB",
                            Name = "Bidón Blando Running Flexible 500ml",
                            Price = 140.00m,
                            Sku = "SKU-228",
                            Stock = 35
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333229"),
                            Currency = "BOB",
                            Name = "Linterna Frontal Running Recargable",
                            Price = 210.00m,
                            Sku = "SKU-229",
                            Stock = 18
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333230"),
                            Currency = "BOB",
                            Name = "Bastones Trail Plegables Carbono",
                            Price = 680.00m,
                            Sku = "SKU-230",
                            Stock = 5
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333231"),
                            Currency = "USD",
                            Name = "Plantillas Amortiguacion Running",
                            Price = 28.00m,
                            Sku = "SKU-231",
                            Stock = 30
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333232"),
                            Currency = "USD",
                            Name = "Plantillas Soporte Arco Running",
                            Price = 35.00m,
                            Sku = "SKU-232",
                            Stock = 25
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333233"),
                            Currency = "USD",
                            Name = "Foam Roller Recuperación Muscular",
                            Price = 32.00m,
                            Sku = "SKU-233",
                            Stock = 22
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333234"),
                            Currency = "USD",
                            Name = "Pelota Masaje Liberación Miofascial",
                            Price = 12.00m,
                            Sku = "SKU-234",
                            Stock = 40
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333235"),
                            Currency = "USD",
                            Name = "Banda Elástica Mini Band Running x3",
                            Price = 15.00m,
                            Sku = "SKU-235",
                            Stock = 35
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333236"),
                            Currency = "USD",
                            Name = "Compresor Pierna Running Medias",
                            Price = 40.00m,
                            Sku = "SKU-236",
                            Stock = 28
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333237"),
                            Currency = "USD",
                            Name = "Spray Antifricción Running",
                            Price = 9.50m,
                            Sku = "SKU-237",
                            Stock = 50
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333238"),
                            Currency = "USD",
                            Name = "Crema Muscular Calor Pre-Entreno",
                            Price = 11.00m,
                            Sku = "SKU-238",
                            Stock = 44
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333239"),
                            Currency = "USD",
                            Name = "Gel Energético Running Carbohidratos",
                            Price = 2.50m,
                            Sku = "SKU-239",
                            Stock = 80
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333240"),
                            Currency = "USD",
                            Name = "Gel Isotónico Sales Minerales Running",
                            Price = 2.90m,
                            Sku = "SKU-240",
                            Stock = 80
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333241"),
                            Currency = "EUR",
                            Name = "Barritas Energéticas Avena Running x5",
                            Price = 9.00m,
                            Sku = "SKU-241",
                            Stock = 65
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333242"),
                            Currency = "EUR",
                            Name = "Bebida Isotónica Polvo Running 1kg",
                            Price = 28.00m,
                            Sku = "SKU-242",
                            Stock = 20
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333243"),
                            Currency = "EUR",
                            Name = "Proteína Recuperación Post-Running 1kg",
                            Price = 49.00m,
                            Sku = "SKU-243",
                            Stock = 14
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333244"),
                            Currency = "EUR",
                            Name = "Cápsulas Sales Minerales Running x60",
                            Price = 16.50m,
                            Sku = "SKU-244",
                            Stock = 35
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333245"),
                            Currency = "EUR",
                            Name = "Magnesio Recuperación Muscular x90",
                            Price = 18.00m,
                            Sku = "SKU-245",
                            Stock = 30
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333246"),
                            Currency = "EUR",
                            Name = "Colágeno Articular Running x30",
                            Price = 22.00m,
                            Sku = "SKU-246",
                            Stock = 22
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333247"),
                            Currency = "EUR",
                            Name = "Omega 3 Antiinflamatorio Deportivo",
                            Price = 19.50m,
                            Sku = "SKU-247",
                            Stock = 28
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333248"),
                            Currency = "EUR",
                            Name = "Vitamina D3 Atleta Rendimiento x60",
                            Price = 14.00m,
                            Sku = "SKU-248",
                            Stock = 40
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333249"),
                            Currency = "EUR",
                            Name = "Chukuanuta Fruta Bolivia Energía x10",
                            Price = 5.50m,
                            Sku = "SKU-249",
                            Stock = 60
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333250"),
                            Currency = "EUR",
                            Name = "Kit Nutrición Running Maratón Completo",
                            Price = 65.00m,
                            Sku = "SKU-250",
                            Stock = 6
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333251"),
                            Currency = "USD",
                            Name = "Cinta Kinesiológica Running Rodilla",
                            Price = 9.00m,
                            Sku = "SKU-251",
                            Stock = 45
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333252"),
                            Currency = "USD",
                            Name = "Tobillera Ligamento Running",
                            Price = 22.00m,
                            Sku = "SKU-252",
                            Stock = 20
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333253"),
                            Currency = "USD",
                            Name = "Rodillera Patelar Running Soporte",
                            Price = 25.00m,
                            Sku = "SKU-253",
                            Stock = 18
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333254"),
                            Currency = "USD",
                            Name = "Manga Gemelar Compresión Running",
                            Price = 18.00m,
                            Sku = "SKU-254",
                            Stock = 30
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333255"),
                            Currency = "USD",
                            Name = "Esparadrapo Rígido Prevención Running",
                            Price = 6.50m,
                            Sku = "SKU-255",
                            Stock = 35
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333256"),
                            Currency = "USD",
                            Name = "Bolsa Hielo Instantánea Running x5",
                            Price = 8.00m,
                            Sku = "SKU-256",
                            Stock = 50
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333257"),
                            Currency = "USD",
                            Name = "Crema Reparadora Pies Runner",
                            Price = 10.50m,
                            Sku = "SKU-257",
                            Stock = 40
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333258"),
                            Currency = "USD",
                            Name = "Ampollas Lubricantes Prevención Pies",
                            Price = 7.00m,
                            Sku = "SKU-258",
                            Stock = 55
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333259"),
                            Currency = "USD",
                            Name = "Protector Solar Deporte SPF50 Running",
                            Price = 14.00m,
                            Sku = "SKU-259",
                            Stock = 38
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333260"),
                            Currency = "USD",
                            Name = "Gafas Running Polarizadas UV400",
                            Price = 55.00m,
                            Sku = "SKU-260",
                            Stock = 11
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333261"),
                            Currency = "EUR",
                            Name = "Gafas Trail Running Intercambiables",
                            Price = 80.00m,
                            Sku = "SKU-261",
                            Stock = 8
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333262"),
                            Currency = "EUR",
                            Name = "Correa Medicion Lactato Running",
                            Price = 220.00m,
                            Sku = "SKU-262",
                            Stock = 3
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333263"),
                            Currency = "EUR",
                            Name = "Plataforma Running Análisis Pisada",
                            Price = 350.00m,
                            Sku = "SKU-263",
                            Stock = 2
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333264"),
                            Currency = "EUR",
                            Name = "Cuerda Salto Cross Training Velocidad",
                            Price = 18.00m,
                            Sku = "SKU-264",
                            Stock = 20
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333265"),
                            Currency = "EUR",
                            Name = "Cronómetro Digital Deporte Running",
                            Price = 24.00m,
                            Sku = "SKU-265",
                            Stock = 15
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333266"),
                            Currency = "EUR",
                            Name = "Cuaderno Entrenamiento Running Diario",
                            Price = 12.00m,
                            Sku = "SKU-266",
                            Stock = 25
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333267"),
                            Currency = "EUR",
                            Name = "App Premium Plan Entrenamiento Running",
                            Price = 9.99m,
                            Sku = "SKU-267",
                            Stock = 999
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333268"),
                            Currency = "EUR",
                            Name = "Bolsa Deporte Running Grande",
                            Price = 38.00m,
                            Sku = "SKU-268",
                            Stock = 30
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333269"),
                            Currency = "EUR",
                            Name = "Toalla Microfibra Deporte Compacta",
                            Price = 14.50m,
                            Sku = "SKU-269",
                            Stock = 45
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333270"),
                            Currency = "EUR",
                            Name = "Muda Ropa Running Set Completo",
                            Price = 70.00m,
                            Sku = "SKU-270",
                            Stock = 12
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333271"),
                            Currency = "BOB",
                            Name = "Cinta Correr Plegable Hogar Running",
                            Price = 3500.00m,
                            Sku = "SKU-271",
                            Stock = 4
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333272"),
                            Currency = "BOB",
                            Name = "Steps Plataforma Escalon Entrenamiento",
                            Price = 780.00m,
                            Sku = "SKU-272",
                            Stock = 6
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333273"),
                            Currency = "BOB",
                            Name = "Colchoneta Yoga Stretching Running",
                            Price = 250.00m,
                            Sku = "SKU-273",
                            Stock = 20
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333274"),
                            Currency = "BOB",
                            Name = "Balón Medicinal 3kg Fuerza Running",
                            Price = 420.00m,
                            Sku = "SKU-274",
                            Stock = 8
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333275"),
                            Currency = "BOB",
                            Name = "TRX Suspensión Complemento Running",
                            Price = 680.00m,
                            Sku = "SKU-275",
                            Stock = 5
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333276"),
                            Currency = "BOB",
                            Name = "Rueda Abdominales Runner Core",
                            Price = 120.00m,
                            Sku = "SKU-276",
                            Stock = 15
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333277"),
                            Currency = "BOB",
                            Name = "Pesas Tobillera 0.5kg Running Fuerza",
                            Price = 95.00m,
                            Sku = "SKU-277",
                            Stock = 22
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333278"),
                            Currency = "BOB",
                            Name = "Escalera Agilidad Running Velocidad",
                            Price = 190.00m,
                            Sku = "SKU-278",
                            Stock = 10
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333279"),
                            Currency = "BOB",
                            Name = "Set Conos Entrenamiento Trail Técnica",
                            Price = 145.00m,
                            Sku = "SKU-279",
                            Stock = 12
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333280"),
                            Currency = "BOB",
                            Name = "Pistola Masaje Percusión Muscular",
                            Price = 1200.00m,
                            Sku = "SKU-280",
                            Stock = 7
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333281"),
                            Currency = "USD",
                            Name = "Sujetador Deportivo Running Alto Impacto",
                            Price = 38.00m,
                            Sku = "SKU-281",
                            Stock = 28
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333282"),
                            Currency = "USD",
                            Name = "Leggins Compresión Running Larga",
                            Price = 45.00m,
                            Sku = "SKU-282",
                            Stock = 22
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333283"),
                            Currency = "USD",
                            Name = "Top Running Cropped Transpirable",
                            Price = 25.00m,
                            Sku = "SKU-283",
                            Stock = 30
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333284"),
                            Currency = "USD",
                            Name = "Set Running Mujer Camiseta + Leggin",
                            Price = 55.00m,
                            Sku = "SKU-284",
                            Stock = 14
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333285"),
                            Currency = "USD",
                            Name = "Zapatilla Running Mujer Amortiguación",
                            Price = 120.00m,
                            Sku = "SKU-285",
                            Stock = 16
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333286"),
                            Currency = "USD",
                            Name = "Chaleco Técnico Running Bolsillos",
                            Price = 48.00m,
                            Sku = "SKU-286",
                            Stock = 18
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333287"),
                            Currency = "USD",
                            Name = "Visor Running Ligero Sin Copa",
                            Price = 16.00m,
                            Sku = "SKU-287",
                            Stock = 35
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333288"),
                            Currency = "USD",
                            Name = "Funda Impermeable Reloj Running",
                            Price = 10.00m,
                            Sku = "SKU-288",
                            Stock = 25
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333289"),
                            Currency = "USD",
                            Name = "Cargador Solar Batería Running Outdoor",
                            Price = 50.00m,
                            Sku = "SKU-289",
                            Stock = 8
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333290"),
                            Currency = "USD",
                            Name = "Botiquín Emergencia Trail Running",
                            Price = 32.00m,
                            Sku = "SKU-290",
                            Stock = 10
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333291"),
                            Currency = "EUR",
                            Name = "Termómetro Digital Deportivo Running",
                            Price = 22.00m,
                            Sku = "SKU-291",
                            Stock = 14
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333292"),
                            Currency = "EUR",
                            Name = "Medias de Recuperación Compresión Post",
                            Price = 35.00m,
                            Sku = "SKU-292",
                            Stock = 20
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333293"),
                            Currency = "EUR",
                            Name = "Bañera Inflable Baño Frío Recuperación",
                            Price = 120.00m,
                            Sku = "SKU-293",
                            Stock = 3
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333294"),
                            Currency = "EUR",
                            Name = "Pulsera Motivacional Running Silicona",
                            Price = 4.50m,
                            Sku = "SKU-294",
                            Stock = 70
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333295"),
                            Currency = "EUR",
                            Name = "Medalla Personalizada Finisher Running",
                            Price = 7.00m,
                            Sku = "SKU-295",
                            Stock = 50
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333296"),
                            Currency = "EUR",
                            Name = "Número Dorsal Running Personalizado",
                            Price = 5.00m,
                            Sku = "SKU-296",
                            Stock = 40
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333297"),
                            Currency = "EUR",
                            Name = "Chip Tiempo Running Cronometraje",
                            Price = 12.00m,
                            Sku = "SKU-297",
                            Stock = 15
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333298"),
                            Currency = "EUR",
                            Name = "Suplemento Precarga Betaín Running",
                            Price = 24.00m,
                            Sku = "SKU-298",
                            Stock = 25
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333299"),
                            Currency = "EUR",
                            Name = "Electrolitos Running Pastillas x60",
                            Price = 13.50m,
                            Sku = "SKU-299",
                            Stock = 45
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333300"),
                            Currency = "EUR",
                            Name = "Kit Completo Atleta Running Iniciación",
                            Price = 199.00m,
                            Sku = "SKU-300",
                            Stock = 5
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
